name: "Invertus php-cs-fixer"
author: Invertus
description: "Possibility to run a php-cs-fixer on your project without adding it as a dependency."
branding:
  icon: "check"
  color: "blue"
inputs:
  other-cmds:
    description: "Add some configs"
    required: false
    default: "/github/workspace --path-mode=intersection"
  working-directory:
    description: "Working directory"
    required: false
    default: "./"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.working-directory }}
    - ${{ inputs.other-cmds }}
